import Head from "next/head";
import Image from "next/image";
import { LoginCard } from "../../components/login-card/LoginCard";
import { SignUpCard } from "../../components/signup-card/SignUpCard";
import { SubmitProjectForm } from "../../components/submit-project-form/SubmitProjectForm";
import { withProtected } from "../../hooks/route";
import styles from "../../styles/Home.module.css";

function Home() {
  return (
    <div>
      <Head>
        <title>Submit Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="pageContainer">
          {" "}
          <SubmitProjectForm />
        </div>
      </main>
    </div>
  );
}

// export default withProtected(Home);
export default Home;
