import Head from "next/head";
import Image from "next/image";
import { LoginCard } from "../../components/login-card/LoginCard";
import { SignUpCard } from "../../components/signup-card/SignUpCard";
import styles from "../../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Signup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="pageContainer">
          {" "}
          <SignUpCard />
        </div>
      </main>
    </div>
  );
}
